# Generated by Django 4.2.4 on 2023-09-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_alter_productregister_pcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='cImage',
            field=models.ImageField(default='null.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='productregister',
            name='pImage',
            field=models.ImageField(default='null.jpg', upload_to='media'),
        ),
    ]
