# Generated by Django 4.2.4 on 2023-09-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='udob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userregister',
            name='uphonenumber',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
