# Generated by Django 4.2.4 on 2023-09-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='udob',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userregister',
            name='uaddress',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
