# Generated by Django 4.2.4 on 2023-09-30 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_remove_userregister_udob_shippingaddress_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='country',
            new_name='town',
        ),
    ]
