# Generated by Django 4.2.4 on 2023-09-30 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_productregister_pstatus'),
        ('User', '0006_rename_country_shippingaddress_town'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('total', models.CharField(max_length=50, null=True)),
                ('cartid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.cart')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.productregister')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.userregister')),
            ],
        ),
    ]
