# Generated by Django 4.2.4 on 2023-09-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_bill',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
