# Generated by Django 4.2.4 on 2023-10-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_alter_order_orderdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderquantity',
            field=models.IntegerField(null=True),
        ),
    ]
