# Generated by Django 4.2.4 on 2023-10-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_order_discount_order_tax_delete_customemaildevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='each_product_total',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_bill',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
    ]
