# Generated by Django 4.2.4 on 2023-10-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_order_each_product_total_alter_order_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userfeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50, null=True)),
                ('uemail', models.CharField(max_length=50, null=True)),
                ('umessage', models.TextField(max_length=100, null=True)),
            ],
        ),
    ]
